repos:

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
      exclude: '^.*migrations.*$'

- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black
      args: [--line-length=100, --target-version=py37]
      exclude: '^.*migrations.*$'

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: trailing-whitespace
    - id: debug-statements
    - id: check-yaml
    - id: name-tests-test
      args: ['--django']
    - id: flake8
      exclude: '^.*migrations.*$'
      additional_dependencies: [
        'flake8-comprehensions',
        'flake8-pep3101',
      ]
