repos:

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
      exclude: '^.*migrations.*$'

- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black
      args: [--line-length=100, --target-version=py37]
      exclude: '^.*migrations.*$'

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: debug-statements
    - id: check-yaml
    - id: name-tests-test
      args: ['--django']
    - id: flake8
      exclude: '^.*migrations.*$'
      additional_dependencies: [
        'flake8-comprehensions',
        'flake8-pep3101',
      ]

- repo: https://github.com/prettier/prettier
  rev: '1.18.2' # Use the sha or tag you want to point at
  hooks:
    - id: prettier
      files: '^.*\.tsx?$'

- repo: local
  hooks:
  - id: eslint
    name: eslint
    files: '^.*\.tsx?$'
    language: system
    pass_filenames: true
    entry: ./frontend/node_modules/.bin/eslint -c "./frontend/.eslintrc" --color
