# Generated by Django 2.2 on 2019-07-25 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('code', models.IntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='The phone number to receive the texts', max_length=128, region=None)),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='weatherwarner.PostalCode')),
            ],
        ),
    ]
