# Generated by Django 2.2 on 2019-08-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherwarner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
