# Generated by Django 2.2 on 2019-08-10 13:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('weatherwarner', '0002_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='The phone number to receive the texts', max_length=128, region=None, unique=True),
        ),
    ]
