# Generated by Django 2.2 on 2019-08-11 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherwarner', '0003_unsubscribes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.AddField(
            model_name='recipient',
            name='postcode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weatherwarner.PostCode'),
            preserve_default=False,
        ),
    ]
