# Generated by Django 2.2 on 2019-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherwarner', '0003_unsubscribes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
