# Generated by Django 2.2 on 2019-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherwarner', '0004_shorten_name_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('forecast_type', models.CharField(choices=[('DEFAULT', 'Default'), ('RAIN', 'Rain'), ('WIND', 'Wind'), ('HOT', 'Hot'), ('COLD', 'Cold')], default='DEFAULT', max_length=8)),
            ],
        ),
    ]
