# Generated by Django 2.2 on 2019-08-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherwarner', '0004_auto_20190811_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='postal_code',
        ),
        migrations.DeleteModel(
            name='PostalCode',
        ),
    ]
